language: go

go:
  - "1.9.4"
  - "1.10"

env:
  - ARCH=x86_64
  - ARCH=i686

branches:
  only:
  - master

script:
- diff -au <(gofmt -d .) <(printf "")
- go test -v -short ./... -args -server=play.minio.io:9000 -access=Q3AM3UQ867SPQQA43P2F -secret=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG